---
development:
  cloud_name: dplfg2dnt
  api_key: '388235819948588'
  api_secret: 0AaSzK5n5s2e4VEMn1o5fCdYiCA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dplfg2dnt
  api_key: '388235819948588'
  api_secret: 0AaSzK5n5s2e4VEMn1o5fCdYiCA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dplfg2dnt
  api_key: '388235819948588'
  api_secret: 0AaSzK5n5s2e4VEMn1o5fCdYiCA
  enhance_image_tag: true
  static_image_support: false
