# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

@animateBooks = ->
  bookBounce = new Bounce
  bookBounce.skew(
    from:
      x: 0
      y: 0
    to:
      x: 40
      y: 60
    easing: 'sway'
    duration: 750
    bounces: 4).scale
    from:
      x: 0.5
      y: 0.5
    to:
      x: 1
      y: 1
    easing: 'bounce'
    duration: 750
    bounces: 4
  # ---
  # generated by coffee-script 1.9.2
  $ ->
    $('.rating-stars').raty
      readOnly: true
      score: ->
        $(this).attr 'data-score'
    bookBounce.applyTo $('.book')
    return

