# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/



navbarBounce = new Bounce
navbarBounce
.translate(
  from:
    x: 300
    y: 0
  to:
    x: 0
    y: 0
  duration: 600
  stiffness: 4)
.scale(
  from:
    x: 1
    y: 1
  to:
    x: 0.1
    y: 2.3
  easing: 'sway'
  duration: 800
  delay: 65
  stiffness: 2)
.scale
  from:
    x: 1
    y: 1
  to:
    x: 5
    y: 1
  easing: 'sway'
  duration: 300
  delay: 30
bookBounce = new Bounce
bookBounce.skew(
  from:
    x: 0
    y: 0
  to:
    x: 40
    y: 60
  easing: 'sway'
  duration: 750
  bounces: 4)
.scale
  from:
    x: 0.5
    y: 0.5
  to:
    x: 1
    y: 1
  easing: 'bounce'
  duration: 750
  bounces: 4

$ ->
# Bounce logo
  bookBounce.applyTo $('.book')
  navbarBounce.applyTo $('.navbar-right')
  return

# ---
# generated by js2coffee 2.1.0